addpath('func');
addpath('func/aes');
addpath('func/classic');
addpath('materi');
addpath('materi/Rijndael_Animation_v4_eng');
addpath('img');
addpath('etc');
addpath('etc/aes dimas');
addpath('etc/aes hilmi');
addpath('etc/aes hilmi/aes-dec');
addpath('etc/aes hilmi/aes-enc');
addpath('etc/aes hilmi/old');